# Generated by Django 4.2.3 on 2023-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0004_itenscompra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="quantidade",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
