# Generated by Django 4.2.4 on 2023-08-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0005_alter_livro_preco_alter_livro_quantidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
