# Generated by Django 4.2.4 on 2023-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0006_autor_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscompra",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
