# Generated by Django 4.2.4 on 2023-08-24 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0008_alter_itenscompra_preco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itenscompra",
            old_name="preco",
            new_name="preco_item",
        ),
    ]
