# Generated by Django 4.2.4 on 2023-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0009_rename_preco_itenscompra_preco_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="preco_item",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
