# Generated by Django 4.2.4 on 2023-08-31 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0010_alter_itenscompra_preco_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="data_compra",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
