# Generated by Django 4.2.4 on 2023-08-31 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0011_compra_data_compra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compra",
            old_name="data_compra",
            new_name="data",
        ),
    ]
