# Generated by Django 4.2.5 on 2023-09-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0012_rename_data_compra_compra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="data",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
