# Generated by Django 4.2.5 on 2023-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0013_alter_compra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de crédito'), (2, 'Cartão de débito'), (3, 'Pix'), (4, 'Boleto'), (5, 'Transferência bancária'), (6, 'Outros')], default=1),
        ),
    ]
