# Generated by Django 4.2.5 on 2023-10-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente')], default='CLIENTE', max_length=50, verbose_name='Type'),
        ),
    ]
